# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/xstofai',
                'doc_host': 'https://xstof.github.io',
                'git_url': 'https://github.com/xstof/xstofai',
                'lib_path': 'xstofai'},
  'syms': {'xstofai.core': {'xstofai.core.foo': ('core.html#foo', 'xstofai/core.py')}}}
