project:
  type: website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  title: "Christof's AI-related notes"
  description: "Repository for AI-related learning and experiments"
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
  sidebar:
    style: floating

metadata-files: [nbdev.yml, sidebar.yml]